import { eq } from "drizzle-orm";
import { getDb, videos, transcripts } from "../index";
import type { Video, NewVideo, Transcript, NewTranscript } from "../schema";
import { z } from "zod";

// Generate a simple unique ID
function generateId() {
  return Date.now().toString(36) + Math.random().toString(36).slice(2);
}

export interface TranscriptSegment {
  start: number;
  end: number;
  text: string;
}

const transcriptSegmentSchema = z.object({
  start: z.number(),
  end: z.number(),
  text: z.string(),
});

const transcriptSegmentsSchema = z.array(transcriptSegmentSchema);

const parseTranscriptSegments = (raw: string | null): TranscriptSegment[] => {
  if (!raw) return [];
  try {
    const parsed: unknown = JSON.parse(raw);
    const validated = transcriptSegmentsSchema.safeParse(parsed);
    return validated.success ? validated.data : [];
  } catch {
    return [];
  }
};

export interface VideoWithTranscripts extends Video {
  transcripts: Array<{
    language: string;
    isAutoGenerated: boolean;
    segments: TranscriptSegment[];
  }>;
}

// Get all videos
export function getAllVideos(): Video[] {
  return getDb().select().from(videos).all();
}

// Get video by ID
export function getVideoById(id: string): Video | undefined {
  return getDb().select().from(videos).where(eq(videos.id, id)).get();
}

// Get video with all transcripts
export function getVideoWithTranscripts(
  id: string
): VideoWithTranscripts | undefined {
  const video = getVideoById(id);
  if (!video) return undefined;

  const videoTranscripts = getDb()
    .select()
    .from(transcripts)
    .where(eq(transcripts.videoId, id))
    .orderBy(transcripts.isAutoGenerated)
    .all();

  return {
    ...video,
    transcripts: videoTranscripts.map((t) => ({
      language: t.language,
      isAutoGenerated: t.isAutoGenerated ?? false,
      segments: parseTranscriptSegments(t.segmentsJson),
    })),
  };
}

// Get all videos with their primary transcript
export function getAllVideosWithPrimaryTranscript(): Array<
  Video & { transcript?: { language: string; segments: TranscriptSegment[] } }
> {
  const allVideos = getAllVideos();

  return allVideos.map((video) => {
    // Get the first transcript (prefer non-auto-generated)
    const transcript = getDb()
      .select()
      .from(transcripts)
      .where(eq(transcripts.videoId, video.id))
      .orderBy(transcripts.isAutoGenerated)
      .get();

    if (!transcript) {
      return video;
    }

    const segments = parseTranscriptSegments(transcript.segmentsJson);

    return {
      ...video,
      transcript: {
        language: transcript.language,
        segments,
      },
    };
  });
}

// Insert or update video
// The localPath record is written only through updateVideoLocalPath.
export function upsertVideo(
  videoData: Omit<NewVideo, "createdAt" | "updatedAt" | "localPath">
): Video {
  const now = Date.now();
  const existing = getVideoById(videoData.id);

  if (existing) {
    const nextVideoData: Omit<NewVideo, "createdAt" | "updatedAt" | "localPath"> = {
      id: videoData.id,
      title: videoData.title,
      channelTitle: videoData.channelTitle,
      duration: videoData.duration,
      thumbnailUrl:
        videoData.thumbnailUrl === undefined
          ? existing.thumbnailUrl
          : videoData.thumbnailUrl,
      description:
        videoData.description === undefined
          ? existing.description
          : videoData.description,
    };

    getDb().update(videos)
      .set({ ...nextVideoData, updatedAt: now })
      .where(eq(videos.id, videoData.id))
      .run();
  } else {
    const nextVideoData: Omit<NewVideo, "createdAt" | "updatedAt"> = {
      id: videoData.id,
      title: videoData.title,
      channelTitle: videoData.channelTitle,
      duration: videoData.duration,
      thumbnailUrl: videoData.thumbnailUrl ?? null,
      localPath: null,
      description: videoData.description ?? null,
    };

    getDb().insert(videos)
      .values({ ...nextVideoData, createdAt: now, updatedAt: now })
      .run();
  }

  return getVideoById(videoData.id)!;
}

// Saved Offline copy locations; only the Offline copy module reads and writes these.
export function getOfflineCopyRecords() {
  return getDb()
    .select({ videoId: videos.id, uri: videos.localPath })
    .from(videos)
    .all()
    .filter((row): row is { videoId: string; uri: string } => !!row.uri);
}

// Update video local path
export function updateVideoLocalPath(id: string, localPath: string | null) {
  getDb().update(videos)
    .set({ localPath, updatedAt: Date.now() })
    .where(eq(videos.id, id))
    .run();
}

// Delete video
export function deleteVideo(id: string) {
  getDb().delete(videos).where(eq(videos.id, id)).run();
}

// Add or update transcript for video
export function upsertTranscript(
  videoId: string,
  language: string,
  segments: TranscriptSegment[],
  isAutoGenerated = false
): Transcript {
  const now = Date.now();

  // Check if transcript exists
  const existing = getDb()
    .select()
    .from(transcripts)
    .where(eq(transcripts.videoId, videoId))
    .all()
    .find((t) => t.language === language);

  const segmentsJson = JSON.stringify(segments);
  if (existing) {
    getDb().update(transcripts)
      .set({ segmentsJson, isAutoGenerated, updatedAt: now })
      .where(eq(transcripts.id, existing.id))
      .run();
    return getDb()
      .select()
      .from(transcripts)
      .where(eq(transcripts.id, existing.id))
      .get()!;
  }

  const id = generateId();
  getDb().insert(transcripts)
    .values({
      id,
      videoId,
      language,
      isAutoGenerated,
      segmentsJson,
      createdAt: now,
      updatedAt: now,
    })
    .run();

  return getDb().select().from(transcripts).where(eq(transcripts.id, id)).get()!;
}

// Get all transcripts for a video
export function getTranscriptsForVideo(videoId: string): Transcript[] {
  return getDb()
    .select()
    .from(transcripts)
    .where(eq(transcripts.videoId, videoId))
    .all();
}

// Get available languages for a video
export function getAvailableLanguages(videoId: string): string[] {
  const videoTranscripts = getTranscriptsForVideo(videoId);
  return videoTranscripts.map((t) => t.language);
}
